SyncaLogger.Web/Controllers/SyncaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using AspNet.Security.OAuth.GitLab;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Newtonsoft.Json;
using SyncaLogger.Web.Models;
using X.PagedList;

namespace SyncaLogger.Web.Controllers
{
    public class SyncaController : Controller
    {
        // GET: Log

        private readonly IHttpClientFactory _httpClient;

        public SyncaController(IHttpClientFactory httpClient)
        {
            _httpClient = httpClient;
           
        }


        [Authorize]
        public async Task<ActionResult> LogById(int id)
        {

            using (var client = _httpClient.CreateClient())
            {
                client.BaseAddress = new Uri("https://localhost:5001/api/");

                if (HttpContext.User.Claims.FirstOrDefault(x => x.Type == "JWT") != null)
                {

                    var jwtSaved = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "JWT").Value;
                    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + jwtSaved);
                }

                var response = await client.GetAsync($"log/{id}");

                string jsonResult = await response.Content.ReadAsStringAsync();

                ApiLog logModel = JsonConvert.DeserializeObject<ApiLog>(jsonResult);

                return View(logModel);
            }

        }

       
        [HttpGet]
       // [Authorize]
        public async Task<ActionResult> Search(SearchFilter filter,int p=1,int s = 10)
        {
            UriBuilder builder = new UriBuilder("https://localhost:5001/api/log");

            ViewBag.Page = p;
            ViewBag.Limit = s;
            builder.Query = $"page={p}" +
                $"&pagelimit={s}" +
                $"&after={filter.AfterThisDate.ToString("yyyyMMddHHmmss")}" +
                $"&before={filter.BeforeThisDate.ToString("yyyyMMddHHmmss")}" +
                $"&level={filter.LogLevel}" +
                $"&asc={filter.SortType}";

            using (var client = _httpClient.CreateClient())
            {
                if (HttpContext.User.Claims.FirstOrDefault(x => x.Type == "JWT") != null)
                {

                    var jwtSaved = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "JWT").Value;
                    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + jwtSaved);
                }

                var response = await client.GetAsync(builder.Uri);

                if (!response.IsSuccessStatusCode)
                {
                    string result = await response.Content.ReadAsStringAsync();
                    return Content(result);
                }

                string jsonResult = await response.Content.ReadAsStringAsync();

                var logModel = JsonConvert.DeserializeObject<PagedApiLogs>(jsonResult);

                return View(logModel);
            }
        }


        //[HttpPost]
        //public async Task<ActionResult> Search(SearchFilter filter)
        //{
        //    using (var client = _httpClient.CreateClient())
        //    {
        //        UriBuilder builder = new UriBuilder("https://localhost:5001/api/log");

        //        builder.Query = $"page={filter.Page}" +
        //            $"&pagelimit={filter.PageLimit}" +
        //            $"&after={filter.AfterThisDate.ToString("yyyyMMddHHmmss")}" +
        //            $"&before={filter.BeforeThisDate.ToString("yyyyMMddHHmmss")}" +
        //            $"&level={filter.LogLevel}" +
        //            $"&asc={filter.SortType}";

        //        var response = await client.GetAsync(builder.Uri);

        //        if (!response.IsSuccessStatusCode)
        //        {
        //            string result = await response.Content.ReadAsStringAsync();
        //            return Content(result);
        //        }

        //        string jsonResult = await response.Content.ReadAsStringAsync();

        //        var logModel = JsonConvert.DeserializeObject<IEnumerable<ApiLog>>(jsonResult).AsQueryable();

        //        return View(logModel);
        //    }
        //}
    }
}

SyncaLogger.Web/Views/Synca/LogById.cshtml
@model SyncaLogger.Web.Models.ApiLog

@{
    ViewData["Title"] = "LogById";
}

<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
</div>

SyncaLogger.Web/Views/Synca/Search.cshtml
@model SyncaLogger.Web.Models.PagedApiLogs

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using X.PagedList.Mvc.Core;
@using X.PagedList;


@addTagHelper *, LazZiya.TagHelpers


<div class="row">
    <div class="col-xl-4">@Html.Partial("_searchFormView", new SearchFilter())</div>
    <div class="col-xl-8">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayName("Date")
                    </th>
                    <th>
                        @Html.DisplayName("Level")
                    </th>
                    <th>
                        @Html.DisplayName("Message")
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.logDTOs)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Level)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Text)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<paging 
        page-no="@ViewBag.Page"
        page-size="@ViewBag.Limit"
        total-records="@Model.TotalCount"
        show-total-pages="false"
        show-total-records="false"
        max-displayed-pages="5">>
    
</paging>

SyncaLogger.Web/Views/Synca/_searchFormView.cshtml
@model SyncaLogger.Web.Models.SearchFilter

@using (Html.BeginForm("Search", "Synca", FormMethod.Get))
{

    <p>@Html.LabelFor(model => model.AfterThisDate)</p>
    <p>@Html.EditorFor(model => model.AfterThisDate)</p>

    <p>@Html.LabelFor(model => model.BeforeThisDate)</p>
    <p>@Html.EditorFor(model => model.BeforeThisDate)</p>

    <p>@Html.LabelFor(model => model.LogLevel)</p>
    <p> <select asp-for="LogLevel" asp-items="Html.GetEnumSelectList<SyncaLogLevel>()"></select></p>

    <p>@Html.LabelFor(model => model.SortType)</p>
    <p>@Html.EditorFor(model => model.SortType)</p>


    <p><input type="submit" value="Search" class="btn btn-info" /></p>
}